URL: localhost:8090
Genesis: true
DBPath: ./.data1
Nodes:
  - localhost:8091
Validators:
  - FjpBPDKk68jA1PKk1Az9o3FUUjcDtceoDVTW2gfg1hsvHwhN1vCb8YosB5ARbQgsuwJY6767wwkcEgFGQFWDhk6SYBVRoztTk2Cu8uUA9tosXFFXcfbApobGDiz5rHPBWFe2L2Rdxm1fTDP18q1U7MTkRJA4NntCgRRoexvchoFBtPN
  - 7Uo4QCAQeAiYpqQ9VGdfqXUvWgyyQY87ts4z8n7AjMppMfY5ZFrY2FGUTYxoBM1czHyAPt9XWrNFa1eRj6NaWzLH8Uqm1GsN6AEcCbEQtFP1185rhck46KyZQqWj1e3hrYLaTy3oixV1cK5gktwr7WbKLy3h4Xy52pLx7NDyGsXVZ3o
PrivateKey: 625QvYmiXckquvzxwMKykiLwNFmkz3qeLtSEaybZ9Kj6N2BCkCbWue11vbiKAdV7BJ3CeDakZdjedBFRMMgoKqPM