// Code generated by "stringer -type=Command"; DO NOT EDIT.

package chain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[commandSync-0]
	_ = x[commandGetBlock-1]
	_ = x[commandSendBlock-2]
	_ = x[commandSendTx-3]
}

const _Command_name = "commandSynccommandGetBlockcommandSendBlockcommandSendTx"

var _Command_index = [...]uint8{0, 11, 26, 42, 55}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
